name: green_perk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0 
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1 
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/models/

  fonts:
    - family: Boardley
      fonts:
        - asset: lib/assets/fonts/boardley.ttf
