name: green_perk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.3
  flutter_tflite: ^1.0.1
  go_router: ^13.2.0
  google_generative_ai: ^0.2.0
  image_picker: ^0.8.9
  pedometer: ^4.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/models/

  fonts:
    - family: Boardley
      fonts:
        - asset: lib/assets/fonts/boardley.ttf
    - family: Cy Grotestk Key
      fonts:
        - asset: lib/assets/fonts/cy_grotestk_key.ttf
    - family: Google Sans
      fonts:
        - asset: lib/assets/fonts/google_sans.ttf
