List<String> rewardNames = [
  'Plant a Tree',
  'Google Play Store Credit: \$10',
  'Google Play Store Credit: \$20',
  'Google Play Store Credit: \$50',
  'Google Play Store Credit: \$100',
  'App Store Credit: \$10',
  'App Store Credit: \$20',
  'App Store Credit: \$50',
  'App Store Credit: \$100',
  'Transportation Credit: \$10',
  'Transportation Credit: \$20',
  'Transportation Credit: \$50',
  'Outdoor Adventure Gear Set',
  'Outdoor Education Program',
  'Nature Tour with Professional Tour Guides',
];

List<String> rewardDesc = [
  'Plant a tree and help the nature!',
  '\$10 Google Play credit - ready to use!',
  '\$20 Google Play credit - ready to use!',
  '\$50 Google Play credit - ready to use!',
  '\$100 Google Play credit - ready to use!',
  '\$10 App Store credit - ready to use!',
  '\$20 App Store credit - ready to use!',
  '\$50 App Store credit - ready to use!',
  '\$100 App Store credit - ready to use!',
  '\$10 Transportation credit for you to use public transportation. (Use public transporation to save nature!)',
  '\$20 Transportation credit for you to use public transportation. (Use public transporation to save nature!)',
  '\$50 Transportation credit for you to use public transportation. (Use public transporation to save nature!)',
  'This set includes these: greenperks Backpack, greenperks Sleeping Bag, Multi-tool, greenperks Tent',
  'Outdoor Education Program to teach you how to survive at any condition!',
  'Nature Tour with Professional Tour Guides to show you the beauties of the nature!',
];

List<String> rewardPoints = [
  '500',
  '1500',
  '3000',
  '5000',
  '10000',
  '1500',
  '3000',
  '5000',
  '10000',
  '1500',
  '3000',
  '10000',
  '50000',
  '100000',
  '300000',
];

List<String> rewardIcons = [
  'https://img.icons8.com/color/240/growing-tree.png',
  'https://img.icons8.com/color/240/google-play.png',
  'https://img.icons8.com/color/240/google-play.png',
  'https://img.icons8.com/color/240/google-play.png',
  'https://img.icons8.com/color/240/google-play.png',
  'https://img.icons8.com/color/240/000000/apple-app-store--v1.png',
  'https://img.icons8.com/color/240/000000/apple-app-store--v1.png',
  'https://img.icons8.com/color/240/000000/apple-app-store--v1.png',
  'https://img.icons8.com/color/240/000000/apple-app-store--v1.png',
  'https://img.icons8.com/color/240/000000/bus.png',
  'https://img.icons8.com/color/240/000000/bus.png',
  'https://img.icons8.com/color/240/000000/bus.png',
  'https://img.icons8.com/color/240/000000/trekking-skin-type-2.png',
  'https://img.icons8.com/color/240/000000/climbing.png',
  'https://img.icons8.com/color/240/nature--v2.png',
];
